spring:
  application:
    name: stocker

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update

  datasource:
    url: ${DB_URL}
    username: ${DB_UNAME}
    password: ${DB_PWD}

stocker:
    dev:
      url : http://localhost:8080/
    prod:
      url : https://api-sm2k4.koyeb.app/